import { useEffect, useState } from 'react';
import { Video, Radio, ArrowLeft, Link2 } from 'lucide-react';
import { CapturePanel } from './CapturePanel';
import { contributorRequest, type ContributorVehicle } from '@/lib/contributorApi';

type Props={vehicles:ContributorVehicle[];contactsVerified:boolean;onSaved:()=>void;refresh:()=>Promise<unknown>};
type DriveReference={id:string;vehicle_id:string;title:string;captured_at:string;status:string};

export function ContributionChoices(props:Props){
  const [mode,setMode]=useState<'recorded'|'live'|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function declare(e:React.FormEvent<HTMLFormElement>,vehicle:string){e.preventDefault();setBusy(true);setMessage('');try{await contributorRequest('/vehicles/'+vehicle+'/rc-self-declare','POST',{authorized:true,not_government_verified:true});await props.refresh();setMessage('Self-declaration saved. This is not a government or ownership verification.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  return <section className="space-y-5">
    {props.vehicles.filter(v=>v.rc_uploaded&&v.verification_status==='PENDING').map(v=><form key={v.id} onSubmit={e=>void declare(e,v.id)} className="provider-card space-y-3"><h3 className="font-semibold">{v.number_plate} · Pilot RC declaration</h3><p className="text-xs leading-6 text-slate-400">Government verification is unavailable. Your uploaded RC may be accepted as self-declared for private pilot contributions; public location publishing still needs operator approval.</p><label className="provider-check text-sm"><input required type="checkbox"/>I am authorized to provide this RC and understand it has NOT been verified by the government.</label><button disabled={busy} className="provider-secondary">Save self-declaration</button></form>)}
    {message&&<p role="status" className="provider-notice">{message}</p>}
    <section className="provider-card space-y-4"><p className="provider-eyebrow">03 / CHOOSE HOW TO CONTRIBUTE</p><h2 className="text-2xl font-semibold">Recorded footage or live capture?</h2><p className="text-sm leading-6 text-slate-400">Choose after signing in. Neither option starts camera or GPS access automatically.</p>
      {!mode?<div className="grid gap-4 sm:grid-cols-2"><button className="rounded-xl border border-white/15 p-6 text-left hover:border-emerald-300 focus-visible:outline focus-visible:outline-emerald-300" onClick={()=>setMode('recorded')}><Video className="text-emerald-300"/><strong className="mt-4 block text-lg">Recorded dashcam video</strong><span className="mt-2 block text-sm leading-6 text-slate-400">Keep the original in your Drive. Register a private file reference and the original recording time.</span></button><button className="rounded-xl border border-white/15 p-6 text-left hover:border-emerald-300 focus-visible:outline focus-visible:outline-emerald-300" onClick={()=>setMode('live')}><Radio className="text-emerald-300"/><strong className="mt-4 block text-lg">Live road-facing capture</strong><span className="mt-2 block text-sm leading-6 text-slate-400">Use a phone or browser-visible camera, with separate consent for GPS, video and photos.</span></button></div>:<button className="provider-secondary" onClick={()=>setMode(null)}><ArrowLeft size={15}/>Change contribution type / stop devices</button>}
    </section>
    {mode==='recorded'&&<DriveLinks vehicles={props.vehicles} contactsVerified={props.contactsVerified}/>}
    {mode==='live'&&<CapturePanel vehicles={props.vehicles} contactsVerified={props.contactsVerified} onSaved={props.onSaved}/>}
    {props.vehicles.filter(v=>v.vehicle_use==='PUBLIC').map(v=><PublicLocationChoice key={v.id} vehicle={v}/>)}
  </section>
}

function DriveLinks({vehicles,contactsVerified}:{vehicles:ContributorVehicle[];contactsVerified:boolean}){
  const [links,setLinks]=useState<DriveReference[]>([]),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
  async function refresh(){setLinks(await contributorRequest<DriveReference[]>('/drive-links'))}
  useEffect(()=>{const c=new AbortController();contributorRequest<DriveReference[]>('/drive-links','GET',undefined,c.signal).then(setLinks).catch(e=>{if(!c.signal.aborted)setMessage(e.message)});return()=>c.abort()},[]);
  const eligible=vehicles.filter(v=>v.rc_uploaded&&['SELF_DECLARED','MANUAL_REVIEWED','RTO_VERIFIED'].includes(v.verification_status));
  async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,data=new FormData(form);setBusy(true);setMessage('');try{await contributorRequest('/drive-links','POST',{vehicle_id:data.get('vehicle_id'),title:data.get('title'),url:data.get('url'),captured_at:new Date(String(data.get('captured_at'))).toISOString(),authorized:data.has('authorized'),processing_consent:data.has('processing')});await refresh();form.reset();setMessage('Private reference saved. Drive access has NOT been verified; no video was downloaded or processed.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  async function remove(id:string){setBusy(true);try{await contributorRequest('/drive-links/'+id,'DELETE');await refresh();setMessage('Reference removed. Your original Drive file was not deleted.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
  return <section className="provider-card space-y-4"><div className="flex items-center gap-3"><Link2 className="text-emerald-300"/><h2 className="text-xl font-semibold">Your recorded footage</h2></div><p className="text-sm leading-7 text-slate-400">Upload the recording to your own Google Drive, then paste its file link here. Keep sharing restricted—do not make RC documents or footage public. A link alone does not grant our app access.</p><p className="provider-notice text-xs leading-6">Google Drive OAuth / file access verification is not connected yet. This saves a reference only, not the video bytes. Live capture currently uses private local storage, not Drive. Account sign-in still uses the existing protected database while MongoDB setup is pending.</p>
    <form onSubmit={save} className="space-y-4"><label className="provider-label">Vehicle<select required name="vehicle_id" className="provider-input">{!eligible.length&&<option value="">Submit an RC and declaration first</option>}{eligible.map(v=><option key={v.id} value={v.id}>{v.number_plate}</option>)}</select></label><div className="grid gap-4 sm:grid-cols-2"><label className="provider-label">Recording name<input name="title" required minLength={2} maxLength={120} placeholder="Morning road survey" className="provider-input"/></label><label className="provider-label">Original recording time<input required type="datetime-local" name="captured_at" className="provider-input"/></label></div><label className="provider-label">Google Drive file link<input required type="url" name="url" maxLength={1000} placeholder="https://drive.google.com/file/d/…/view" className="provider-input"/></label><label className="provider-check text-xs leading-6"><input required type="checkbox" name="authorized"/>I own this footage or have permission to share it. I have removed unnecessary personal content.</label><label className="provider-check text-xs leading-6"><input required type="checkbox" name="processing"/>I authorize private road-condition processing after file access is verified. This does not authorize public footage display or model training.</label><button disabled={busy||!contactsVerified||!eligible.length} className="provider-primary">{busy?'Saving…':'Save private file reference'}</button>{!contactsVerified&&<p className="text-xs text-amber-200">Email and phone verification are required. They have not been bypassed.</p>}</form>
    {message&&<p role="status" className="provider-notice">{message}</p>}
    <div className="space-y-3">{links.map(link=><article key={link.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-white/10 p-4"><div><strong className="text-sm">{link.title}</strong><p className="mt-1 text-xs text-amber-200">{link.status.replaceAll('_',' ')}</p><p className="mt-1 text-xs text-slate-500">Recorded {new Date(link.captured_at).toLocaleString()}</p></div><button disabled={busy} className="provider-secondary" onClick={()=>void remove(link.id)}>Remove reference</button></article>)}</div>
  </section>
}

function PublicLocationChoice({vehicle}:{vehicle:ContributorVehicle}){
  const [notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  async function save(enabled:boolean){setBusy(true);setNotice('');try{const r=await contributorRequest<{notice:string}>('/vehicles/'+vehicle.id+'/public-location-consent','PUT',{enabled,camera_mounted:enabled,understands_public_visibility:enabled});setNotice(r.notice)}catch(e){setNotice((e as Error).message)}finally{setBusy(false)}}
  return <section className="provider-card space-y-4"><h3 className="font-semibold">{vehicle.number_plate} · Optional public location</h3><p className="text-xs leading-6 text-slate-400">This is separate from private locality-admin access. Anyone could see the vehicle’s recent location under a public alias. No number plate or footage is shown. Self-declaration alone cannot activate this feature.</p><form onSubmit={e=>{e.preventDefault();void save(true)}} className="space-y-3"><label className="provider-check text-xs leading-6"><input required type="checkbox"/>This public vehicle has a road-facing camera, and I have the operator’s authorization to publish its location.</label><label className="provider-check text-xs leading-6"><input required type="checkbox"/>I understand the location will be visible publicly after operator approval and only during a new permitted sharing session.</label><button disabled={busy} className="provider-secondary">Request public-location approval</button></form><button disabled={busy} className="provider-secondary" onClick={()=>void save(false)}>Disable public location / stop sessions</button>{notice&&<p role="status" className="provider-notice">{notice}</p>}</section>
}
