import { useCallback, useEffect, useState } from 'react';
import { Link } from 'wouter';
import { ArrowLeft, ArrowRight, BusFront, Car, CheckCircle2, Circle, LockKeyhole, LogOut, MapPinned, ShieldCheck, Upload } from 'lucide-react';
import { ContributionChoices } from '@/components/contributors/ContributionChoices';
import { AdminVisibilityPanel } from '@/components/contributors/AdminVisibilityPanel';
import { contributorRequest, contributorUpload, mediaUrl, rcUrl, POLICY_VERSION, type Activity, type Capabilities, type Profile } from '@/lib/contributorApi';
import './contributors.css';
import { MONGO_CONTRIBUTORS } from '@/lib/deployment';

export default function Contributors() {
  const [profile,setProfile]=useState<Profile|null>(null);
  const [loading,setLoading]=useState(true);
  const [mode,setMode]=useState<'register'|'login'>('login');
  const [cap,setCap]=useState<Capabilities|null>(null);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState('');
  const [notice,setNotice]=useState('');
  const [activity,setActivity]=useState<Activity|null>(null);
  const [setup,setSetup]=useState<'PUBLIC'|'PRIVATE'>('PRIVATE');
  const refresh=useCallback(async()=>{const result=await contributorRequest<Profile>('/me');setProfile(result);return result;},[]);
  const refreshActivity=useCallback(()=>{void contributorRequest<Activity>('/activity').then(setActivity).catch(()=>{});},[]);
  useEffect(()=>{
    const controller=new AbortController();
    void contributorRequest<Capabilities>('/capabilities','GET',undefined,controller.signal).then(setCap).catch(()=>setError('Contributor API is unavailable. Start the backend.'));
    void contributorRequest<Profile>('/me','GET',undefined,controller.signal).then(p=>{setProfile(p);refreshActivity();}).catch(()=>{}).finally(()=>setLoading(false));
    return ()=>controller.abort();
  },[refreshActivity]);

  async function action(work:()=>Promise<unknown>,message?:string) {
    setBusy(true);setError('');setNotice('');
    try {await work();if(message)setNotice(message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }

  async function authenticate(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault();const form=new FormData(e.currentTarget);
    await action(async()=>{
      const payload:Record<string,unknown>={email:form.get('email'),password:form.get('password')};
      if(mode==='register')Object.assign(payload,{full_name:form.get('full_name'),phone:form.get('phone'),adult:form.has('adult'),terms_accepted:form.has('terms'),privacy_accepted:form.has('privacy'),policy_version:POLICY_VERSION});
      await contributorRequest('/'+mode,'POST',payload);await refresh();refreshActivity();
    });
  }

  async function addVehicle(e:React.FormEvent<HTMLFormElement>) {
    e.preventDefault();const form=e.currentTarget;const data=new FormData(form);
    await action(async()=>{await contributorRequest('/vehicles','POST',{number_plate:data.get('number_plate'),vehicle_use:setup,setup_type:data.get('setup_type'),authorized:data.has('authorized')});await refresh();form.reset();},'Vehicle added. Upload its RC PNG next.');
  }

  async function uploadRc(id:string,file?:File) {
    if(!file)return;
    if(file.type!=='image/png'||file.size>5*1024*1024){setError('RC must be a PNG image under 5 MB.');return;}
    await action(async()=>{await contributorUpload('/vehicles/'+id+'/rc',file,'PUT');await refresh();},'RC saved privately. Pending review—not RTO verified.');
  }

  return <div className="provider-page">
    <header className="provider-header"><Link href="/" className="flex items-center gap-3 text-slate-200"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-300 text-slate-950"><MapPinned size={21}/></span><span className="font-bold">Drishti <span className="font-normal text-slate-400">/ Contributors</span></span></Link><div className="flex items-center gap-4"><Link href="/gis" className="text-xs text-slate-400 hover:text-white">Road map</Link>{profile&&<button className="provider-secondary" onClick={()=>void action(async()=>{await contributorRequest('/logout','POST');setProfile(null);setActivity(null);})}><LogOut size={15}/>Sign out</button>}</div></header>
    <main className="mx-auto max-w-6xl space-y-6 px-5 py-10">
      <section className="grid gap-8 lg:grid-cols-[1.3fr_1fr]"><div><p className="provider-eyebrow">ROAD INTELLIGENCE / CONTRIBUTOR NETWORK</p><h1 className="mt-4 max-w-xl text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">Your journey.<br/><span className="text-emerald-300">A clearer picture</span><br/>of our roads.</h1><p className="mt-5 max-w-xl text-sm leading-7 text-slate-400">A separate space for vehicle owners and authorized operators who choose to share road-facing footage and GPS. Public transport or a private setup—always opt-in, always under your control.</p><div className="mt-5 flex flex-wrap gap-3 text-xs text-slate-300"><span className="provider-pill"><LockKeyhole size={13}/>Private documents</span><span className="provider-pill"><ShieldCheck size={13}/>Explicit permissions</span><span className="provider-pill"><Circle size={12}/>No background tracking</span></div></div><aside className="provider-card self-center"><p className="provider-eyebrow">HOW IT WORKS</p>{['Create your contributor account','Verify your email and phone','Add a vehicle and submit its RC','Choose devices and start sharing'].map((item,i)=><div key={item} className="mt-5 flex items-center gap-4"><span className="flex h-7 w-7 items-center justify-center rounded-full border border-emerald-300/30 text-xs text-emerald-300">0{i+1}</span><span className="text-sm text-slate-300">{item}</span></div>)}</aside></section>
      {error&&<p role="alert" className="provider-error">{error}</p>}{notice&&<p role="status" className="provider-notice">{notice}</p>}
      {MONGO_CONTRIBUTORS&&<p className="provider-notice text-sm leading-7">MongoDB contributor accounts · {cap?.notice||'Vehicle documents, Drive access and video/GPS ingestion are not connected to this account service yet.'} OmniView will review selected GPS-linked recordings locally in batches—not as live AI detection.</p>}
      {cap&&(!cap.sms_otp||!cap.email_otp||!cap.rto_api)&&<div className="provider-notice text-xs leading-6"><strong className="text-amber-200">Integration status:</strong> SMS OTP {cap.sms_otp?'configured':'not configured'} · Email OTP {cap.email_otp?'configured':'not configured'} · RTO API authorization pending. No test OTP is used. RC self-declaration is not government verification. <a className="underline" href="https://www.apisetu.gov.in/sop" target="_blank" rel="noreferrer">Official API access process</a></div>}
      {loading?<p className="text-slate-400">Checking your session…</p>:!profile?<section className="provider-card mx-auto max-w-2xl">
        <div className="mb-6 flex border-b border-white/10" role="tablist" aria-label="Account form">{(['register','login'] as const).map(m=><button key={m} role="tab" disabled={m==='register'&&MONGO_CONTRIBUTORS&&cap?.registration_enabled!==true} aria-selected={mode===m} className={'px-4 pb-3 text-sm disabled:opacity-40 '+(mode===m?'border-b-2 border-emerald-300 text-emerald-300':'text-slate-500')} onClick={()=>{setMode(m);setError('');}}>{m==='register'?'Become a contributor':'Sign in'}</button>)}</div>
        {MONGO_CONTRIBUTORS&&cap?.registration_enabled!==true&&<p className="provider-notice mb-4 text-sm">Public registration is closed while deployment checks are completed. Existing provisioned accounts can sign in.</p>}
        <form onSubmit={authenticate} className="space-y-4">
          {mode==='register'&&<label className="provider-label">Full name<input required name="full_name" minLength={2} maxLength={120} autoComplete="name" className="provider-input" placeholder="Your name"/></label>}
          <label className="provider-label">Email address<input required type="email" name="email" maxLength={254} autoComplete="email" className="provider-input" placeholder="you@example.com"/></label>
          {mode==='register'&&<label className="provider-label">Indian mobile number<input required type="tel" name="phone" pattern="\+91[6-9][0-9]{9}" autoComplete="tel" className="provider-input" placeholder="+919876543210"/><span className="text-xs font-normal text-slate-500">Include +91. Verification does not establish vehicle ownership.</span></label>}
          <label className="provider-label">Password<input required name="password" type="password" minLength={mode==='register'?12:1} maxLength={128} autoComplete={mode==='register'?'new-password':'current-password'} className="provider-input" placeholder={mode==='register'?'At least 12 characters':'Your password'}/></label>
          {mode==='register'&&<fieldset className="space-y-3 rounded-xl bg-white/[.03] p-4 text-xs leading-5"><legend className="sr-only">Required acknowledgements</legend><label className="provider-check"><input required type="checkbox" name="adult"/>I am at least 18 years old.</label><label className="provider-check"><input required type="checkbox" name="terms"/>I accept the <Link className="text-emerald-300 underline" href="/contribute/privacy">contributor terms</Link>.</label><label className="provider-check"><input required type="checkbox" name="privacy"/>I consent to account/contact/RC processing described in the <Link className="text-emerald-300 underline" href="/contribute/privacy">privacy notice</Link>. GPS and media require separate choices.</label></fieldset>}
          <button disabled={busy} className="provider-primary w-full">{busy?'Please wait…':mode==='register'?'Create contributor account':'Sign in securely'}<ArrowRight size={16}/></button>
        </form><p className="mt-4 text-xs leading-6 text-slate-500">Local pilot—not a government service. Do not upload another person’s documents. Read the notice before registration; production terms need the project operator’s review.</p>
      </section>:<>
        <section className="provider-card"><p className="provider-eyebrow">01 / ACCOUNT & CONTACT VERIFICATION</p><h2 className="mt-2 text-xl font-semibold">Welcome, {profile.user.full_name}</h2><p className="mt-2 text-xs text-slate-400">Contributor access is separate from the normal bus/map pages.</p>
          <div className="mt-5 grid gap-4 md:grid-cols-2">{(['email','sms'] as const).map(channel=>{
            const verified=channel==='email'?profile.user.email_verified:profile.user.phone_verified;
            const available=channel==='email'?cap?.email_otp:cap?.sms_otp;
            return <OtpCard key={channel} channel={channel} destination={channel==='email'?profile.user.email:profile.user.phone} verified={verified} available={!!available} busy={busy} action={action} refresh={refresh}/>;
          })}</div>
        </section>
        {(profile.user.withdrawn_at||profile.user.privacy_version!==POLICY_VERSION)?<section className="provider-card space-y-3"><h2 className="text-xl">Review current sharing consent</h2><p className="text-sm text-slate-400">No new data is accepted. Review the current notice before opting in again.</p><form onSubmit={e=>{e.preventDefault();void action(async()=>{await contributorRequest('/consent','POST',{accepted:true,policy_version:POLICY_VERSION});await refresh();});}}><label className="provider-check text-sm"><input required type="checkbox"/>I accept the current <Link href="/contribute/privacy" className="underline">terms and privacy notice</Link>.</label><button className="provider-primary mt-4">Opt in again</button></form></section>:MONGO_CONTRIBUTORS?<section className="provider-card space-y-3"><h2 className="text-xl">Account ready for the next phase</h2><p className="text-sm leading-7 text-slate-400">You can manage your session, verify contacts and withdraw consent. Vehicle registration, RC storage, private Drive references and video/GPS capture are not connected to MongoDB accounts yet. No device access is requested by this account page.</p></section>:<>
          <section className="provider-card space-y-5"><div><p className="provider-eyebrow">02 / VEHICLE & AUTHORITY</p><h2 className="mt-2 text-xl font-semibold">Register your setup</h2></div>
            <form onSubmit={addVehicle} className="space-y-4"><div className="grid grid-cols-2 gap-3">{(['PRIVATE','PUBLIC'] as const).map(type=><button type="button" key={type} aria-pressed={setup===type} onClick={()=>setSetup(type)} className={'rounded-xl border p-4 text-left '+(setup===type?'border-emerald-300/60 bg-emerald-300/5':'border-white/10')}>{type==='PUBLIC'?<BusFront className="mb-2 text-emerald-300"/>:<Car className="mb-2 text-emerald-300"/>}<strong className="block text-sm">{type==='PUBLIC'?'Public / commercial vehicle':'Private vehicle'}</strong><span className="mt-1 block text-xs text-slate-500">{type==='PUBLIC'?'Bus, taxi, shared transport':'Personal car / private setup'}</span></button>)}</div>
              <div className="grid gap-4 sm:grid-cols-2"><label className="provider-label">Number plate<input required name="number_plate" className="provider-input uppercase" placeholder="DL 1PC 1234" maxLength={20}/></label><label className="provider-label">Capture setup<select name="setup_type" className="provider-input"><option value="PHONE_CAMERA">Phone camera</option><option value="USB_CAMERA">USB / browser-visible dashcam</option><option value="DASHCAM_FILE">Upload dashcam recordings</option></select></label></div>
              <label className="provider-check text-xs leading-6"><input required type="checkbox" name="authorized"/>I own this vehicle or have the owner/operator’s authorization to submit the RC and share road data. For public vehicles, I have the operator’s permission.</label><button disabled={busy} className="provider-secondary">Add vehicle<ArrowRight size={15}/></button>
            </form>
            {profile.vehicles.map(v=><article key={v.id} className="flex flex-wrap items-center justify-between gap-4 rounded-xl border border-white/10 p-4"><div><strong className="tracking-wider">{v.number_plate}</strong><p className="mt-1 text-xs text-slate-400">{v.vehicle_use} · {v.setup_type.replaceAll('_',' ')}</p><p className="mt-2 text-xs text-amber-200">{v.verification_status==='MANUAL_REVIEWED'?'Document manually reviewed · NOT government verified':v.verification_status.replaceAll('_',' ')}</p></div><div className="flex flex-wrap gap-3"><label className="provider-secondary cursor-pointer"><Upload size={15}/>{v.rc_uploaded?'Replace RC PNG':'Upload RC PNG'}<input disabled={busy} className="sr-only" type="file" accept="image/png" aria-label={'RC PNG for '+v.number_plate} onChange={e=>{void uploadRc(v.id,e.target.files?.[0]);e.target.value='';}}/></label>{v.rc_uploaded&&<a className="provider-secondary" href={rcUrl(v.id)} target="_blank" rel="noreferrer">View private RC</a>}<button className="provider-secondary" disabled={busy} onClick={()=>void action(()=>contributorRequest('/vehicles/'+v.id+'/rto-check','POST'))}>Check RTO status</button></div></article>)}
            {profile.vehicles.map(v=><section key={'access-'+v.id} className="rounded-xl border border-white/10 p-4"><h3 className="mb-3 text-sm font-semibold">{v.number_plate} · Local admin visibility</h3><AdminVisibilityPanel vehicle={v} refresh={refresh}/></section>)}
            <p className="text-xs leading-6 text-slate-500">A plate format or RC photo does not prove ownership. Official results require authorized API access; manual document review is labelled separately. Replacing an RC resets review and stops sharing.</p>
          </section>
          <ContributionChoices vehicles={profile.vehicles} contactsVerified={profile.user.email_verified&&profile.user.phone_verified} onSaved={refreshActivity} refresh={refresh}/>
        </>}
        <section className="provider-card space-y-4"><div className="flex items-center justify-between"><div><p className="provider-eyebrow">04 / PRIVATE ACTIVITY</p><h2 className="mt-2 text-xl font-semibold">What you’ve shared</h2></div><button className="provider-secondary" onClick={refreshActivity}>Refresh</button></div><p className="text-xs text-slate-400">Your footage, RC and contacts remain private. Public locations require a separate opt-in and operator approval. Locality-admin observation is a different permission for your active sharing session.</p>
          {!activity?.sessions.length?<p className="py-4 text-sm text-slate-500">No sharing sessions yet. We have not generated sample journeys for you.</p>:<div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="text-slate-500"><tr><th className="py-3">Vehicle / started</th><th>GPS points</th><th>Files</th><th>Status</th></tr></thead><tbody>{activity.sessions.map(s=><tr key={s.id} className="border-t border-white/10"><td className="py-3">{s.number_plate}<br/><span className="text-slate-500">{new Date(s.started_at).toLocaleString()}</span></td><td>{s.gps_points}</td><td>{s.media_files}</td><td>{s.ended_at?'Stopped':new Date(s.expires_at).getTime()<Date.now()?'Expired':'Active'}</td></tr>)}</tbody></table></div>}
          {!!activity?.gps.length&&<div className="rounded-xl bg-white/5 p-4 text-xs"><p className="font-semibold">Latest received GPS</p><p className="mt-2">{activity.gps[0].latitude.toFixed(6)}, {activity.gps[0].longitude.toFixed(6)} · ±{Math.round(activity.gps[0].accuracy_m)} m</p><p className="mt-1 text-slate-500">{new Date(activity.gps[0].captured_at).toLocaleString()} · Precise coordinates are not sent to a third-party map service.</p></div>}
          {!!activity?.media.length&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{activity.media.map(m=><article key={m.id} className="overflow-hidden rounded-xl border border-white/10">{m.kind==='photo'?<img src={mediaUrl(m.id)} className="aspect-video w-full object-contain" alt="Your private road photo"/>:<video src={mediaUrl(m.id)} className="aspect-video w-full" controls preload="metadata"/>}<p className="p-3 text-xs text-slate-400">{new Date(m.captured_at).toLocaleString()} · {(m.byte_size/1024/1024).toFixed(1)} MB</p></article>)}</div>}
        </section>
        <section className="provider-card space-y-4"><h2 className="font-semibold">Privacy controls</h2><p className="text-xs leading-6 text-slate-400">Withdrawal stops new collection. Existing private data remains until retention cleanup or your deletion request is processed. These pilot terms are not a certification of legal compliance.</p><div className="flex flex-wrap gap-3"><button className="provider-secondary" onClick={()=>void action(async()=>{await contributorRequest('/withdraw','POST');await refresh();},'Consent withdrawn. Collection stopped.')}>Withdraw sharing consent</button><button className="provider-secondary text-rose-300" onClick={()=>{if(window.confirm('Request deletion of this contributor account, RC documents, GPS and media? The account will be disabled immediately; the operator must process erasure.'))void action(async()=>{await contributorRequest('/deletion-request','POST');setProfile(null);},'Deletion requested. Your account is disabled and sharing has stopped.');}}>Request account/data deletion</button></div></section>
      </>}
      <footer className="flex flex-wrap justify-between gap-3 border-t border-white/10 pt-6 text-xs text-slate-500"><Link href="/contribute/privacy" className="hover:text-emerald-300">Terms, privacy & data handling</Link><Link href="/admin" className="hover:text-emerald-300">Locality admin desk</Link><span>Local pilot · Never configure devices while driving</span></footer>
    </main>
  </div>;
}

function OtpCard({channel,destination,verified,available,busy,action,refresh}:{channel:'email'|'sms';destination:string;verified:boolean;available:boolean;busy:boolean;action:(work:()=>Promise<unknown>,message?:string)=>Promise<void>;refresh:()=>Promise<unknown>}) {
  const [optIn,setOptIn]=useState(false);const [code,setCode]=useState('');
  return <div className="space-y-3 rounded-xl border border-white/10 p-4"><div className="flex items-center justify-between"><p className="text-sm">{channel==='email'?'Email':'Phone'} verification</p>{verified?<CheckCircle2 size={17} className="text-emerald-300"/>:<Circle size={17} className="text-slate-500"/>}</div><p className="break-all text-xs text-slate-400">{destination}</p>{verified?<p className="text-xs text-emerald-300">Verified by OTP provider</p>:<><label className="provider-check text-xs leading-5"><input type="checkbox" checked={optIn} onChange={e=>setOptIn(e.target.checked)}/>Send this {channel==='email'?'email address':'phone number'} to Twilio{channel==='email'?'/SendGrid':''} to deliver a verification code.</label><button disabled={busy||!available||!optIn} className="provider-secondary w-full" onClick={()=>void action(()=>contributorRequest('/otp/send','POST',{channel,delivery_consent:true}),'OTP requested. It expires in 10 minutes; resend after 60 seconds.')}>{available?'Send OTP':'OTP service not configured'}</button><form className="flex gap-2" onSubmit={e=>{e.preventDefault();void action(async()=>{await contributorRequest('/otp/check','POST',{channel,code});setCode('');await refresh();},'Contact verified.');}}><input aria-label={channel+' OTP'} required pattern="[0-9]{4,10}" inputMode="numeric" autoComplete="one-time-code" className="provider-input min-w-0" value={code} onChange={e=>setCode(e.target.value)} placeholder="Verification code"/><button disabled={busy||!available} className="provider-secondary">Verify</button></form></>}</div>;
}
