import { Link } from 'wouter';
import './contributors.css';
import { CLOUD_DEPLOYMENT, MONGO_CONTRIBUTORS } from '@/lib/deployment';

export default function ContributorPrivacy() {
  return <div className="provider-page"><main className="mx-auto max-w-3xl space-y-6 px-5 py-10"><Link href="/contribute" className="text-sm text-emerald-300">← Contributor portal</Link><p className="provider-eyebrow">LOCAL PILOT NOTICE / 2026-09-04-v2</p><h1 className="text-3xl font-semibold">Contributor terms & privacy</h1><p className="provider-notice">This is a project-pilot notice, not a government service or legal-compliance certification. The project operator must supply its legal identity, contact/grievance address, review retention and vendor contracts, and obtain appropriate advice before public enrollment. Do not invite real contributors until that review is complete.</p>
    {MONGO_CONTRIBUTORS&&<section className="provider-card"><h2 className="font-semibold">MongoDB account pilot — current scope</h2><p className="mt-3 text-sm leading-7 text-slate-400">{CLOUD_DEPLOYMENT?'Cloudflare serves this website and forwards account requests to Render.':'This website currently forwards contributor requests to a separate local account service.'} MongoDB Atlas stores account names, email, phone, salted password hashes and consent records; separate collections store hashed sessions, verification challenge references and rate-limit counters. No raw passwords or OTP codes are stored. This account service does not accept RC documents, footage, GPS or Drive links yet. The descriptions below of those features apply to the separate PostgreSQL pilot or future work. Deletion requests immediately disable access; the operator must complete erasure and backup review. Public registration stays closed until the operator contact, retention schedule and vendor review are completed.</p></section>}
    {[
      ['RC self-declaration','An authorized contributor may attest to their uploaded RC for private pilot contributions. SELF_DECLARED does not mean government verified or proven ownership. Email/phone OTP remains required. Self-declaration cannot authorize public location display. Replacing an RC resets review and stops sharing.'],
      ['Private Drive references','A reference stores the Drive file identifier, optional resource key, recording title/time and contributor/vehicle association. Keep the original file restricted. Drive OAuth and access verification are not connected: saving a link does not download, validate, train on or publish the video. References stay until removed or account-erasure cleanup runs; removing one does not delete your Drive file. Account/reference storage remains PostgreSQL pending secure MongoDB migration. Live media remains in private local storage, not Drive.'],
      ['Optional public-vehicle location','Only camera-mounted public vehicles can request public-map visibility with operator authority and separate explicit consent. Operator approval and a non-identifying public alias are required, plus a fresh active GPS/video session. Public fields are the alias, recent location, timestamp and accuracy, never a plate, owner, RC or footage. Locations older than 90 seconds or with poor accuracy are excluded on refresh. Disabling visibility, stopping or withdrawal denies subsequent access. Previously viewed information cannot be recalled. Private vehicles cannot opt in.'],
      ['Who may participate','Adults (18+) who own the vehicle or are authorized by its owner/operator. For buses, taxis and other public/commercial vehicles, obtain the operator’s permission. Do not upload someone else’s RC or record passengers, homes or private spaces.'],
      ['Account and vehicle data','We store your name, email, phone, a salted password hash, number plate, declared public/private use, setup type, RC image, verification status and consent timestamps. RC images are private and re-encoded without embedded image metadata. A photo or plate-format match does not prove ownership.'],
      ['OTP and government checks','Requesting an OTP sends your chosen email or phone to Twilio Verify; email delivery also uses its SendGrid integration. An independent, unchecked opt-in precedes each channel’s first request in this visit. RTO/API Setu checks require authorized access. No RC is automatically sent to a government or third-party vehicle-data API in this build.'],
      ['GPS, photos and video','Choose GPS, photos and video separately for each sharing session. Preview permissions are local until Start sharing. Browser camera recordings exclude microphone audio; uploaded recordings may contain audio and must be cleaned by you first. Raw footage can contain faces/plates and is not automatically redacted—keep it road-facing and avoid unnecessary personal information.'],
      ['Purpose and access','The pilot collects road-condition and transport-safety research data. Raw media, RCs and contacts are not displayed by public APIs. Private-vehicle GPS is never published. Public-vehicle locations require the separate opt-in and operator approval described below. They are accessible to your account and trusted local system operators. They are not automatically sent to an AI provider or used for model training. No face identification or enforcement decisions are authorized by these terms.'],
      ['Locality observation — separate opt-in (locality-observation-v1)','Vehicle locality is an owner-declared operating assignment, not an official geofence. The two admins assigned to that locality may list public vehicles after the owner acknowledges roster visibility. Private vehicles are hidden unless the owner allows admin observation. For BOTH types, GPS/photos/video need this additional opt-in and the corresponding sharing-session permissions. Only new active sessions are visible; changing locality, stopping, withdrawal or revocation denies further access. Already viewed/downloaded information cannot be recalled. These admins never receive RC images, passwords, email or phone through the desk. Existing vehicles are unassigned by default. Known dummy admin credentials are local-demo only, not appropriate for real deployment.'],
      ['Stop and withdraw','Stop / release devices ends local camera/GPS collection and requests server-side session closure. Hiding/leaving the page pauses capture. Sessions expire after two hours; phones may suspend background browser tabs. Withdraw sharing consent stops further collection; it does not retroactively erase already received data. Request account/data deletion disables the account and queues erasure for the operator’s cleanup command.'],
      ['Retention and limits','Raw GPS and media are available to the contributor for seven days. The operator must run the privacy cleanup command to physically purge expired records/files; there is no automatic scheduled cleanup in this local build. Account and RC records stay until deletion is requested; cleanup then erases them. Consent/audit metadata currently stays with the account rather than a separate legally mandated archive. Quotas: five vehicles, 500 MB media per account, 5 MB images, 25 MB videos and three minutes per clip.'],
      ['Security and safety','This is a local development service. Do not expose it publicly without HTTPS, access-control/security review, encrypted storage/backups, production monitoring and a reviewed privacy process. Do not configure or touch the portal while driving. Use a passenger or configure while parked. This portal does not grant permission to record where it is restricted.'],
      ['Contact and disputes','During the local pilot, contact the project/team operator directly for access, correction, review, withdrawal or erasure. A published legal/operator contact and grievance mechanism must be added before external contributors are onboarded. No official-government affiliation, incentives, insurance or legal protection is promised.'],
    ].map(([title,body])=><section key={title} className="provider-card"><h2 className="font-semibold">{title}</h2><p className="mt-3 text-sm leading-7 text-slate-400">{body}</p></section>)}
    <section className="text-xs leading-7 text-slate-500">Official references: <a className="underline" href="https://www.apisetu.gov.in/sop" target="_blank" rel="noreferrer">API Setu access</a> · <a className="underline" href="https://www.twilio.com/docs/verify/api/verification" target="_blank" rel="noreferrer">Twilio Verify</a> · <a className="underline" href="https://www.meity.gov.in/documents/act-and-policies" target="_blank" rel="noreferrer">MeitY acts and policies</a>.</section>
    </main></div>;
}
