import { useEffect, useState } from 'react';
import { Link } from 'wouter';
import { ArrowUpRight, Map, ShieldCheck, Construction, CheckCircle2, ScanLine, Activity } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { PublicHeader } from '@/components/PublicHeader';
import { publicRequest, type PublicOverview } from '@/lib/publicApi';
import { CLOUD_DEPLOYMENT } from '@/lib/deployment';

export default function PublicHome(){
  const [data,setData]=useState<PublicOverview|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
  useEffect(()=>{const c=new AbortController();setError('');setData(null);publicRequest<PublicOverview>('overview',c.signal).then(setData).catch(e=>{if(!c.signal.aborted)setError(e.message)});return()=>c.abort()},[retry]);
  return <div className="min-h-screen bg-[#04101b] text-slate-200"><PublicHeader/><main className="mx-auto max-w-7xl space-y-8 px-5 py-8">
    <section className="grid gap-6 rounded-3xl border border-white/10 bg-[#091c29] p-6 md:grid-cols-[1.5fr_1fr] md:p-9"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-emerald-300">Public road progress</p><h1 className="mt-4 max-w-2xl text-4xl font-semibold leading-tight tracking-tight md:text-5xl">See the road.<br/>Follow the progress.</h1><p className="mt-4 max-w-xl text-sm leading-7 text-slate-400">Explore West Delhi’s roads, follow published repair updates and see authorized public transport locations. Personal contributor information stays private.</p><Button asChild size="lg" className="mt-6 bg-emerald-300 text-slate-950 hover:bg-emerald-200"><Link href="/gis"><Map size={18}/>Open the public GIS map<ArrowUpRight size={17}/></Link></Button></div><aside className="self-center rounded-2xl border border-emerald-300/20 bg-emerald-300/5 p-6"><ShieldCheck className="text-emerald-300"/><h2 className="mt-4 font-semibold text-white">Public by permission, not by default.</h2><p className="mt-3 text-sm leading-6 text-slate-400">No private-vehicle tracking, number plates, RC documents or raw camera feeds are shown here.</p><p className="mt-4 text-xs text-amber-200">Independent prototype · Not an official government service</p></aside></section>
    {error&&<div role="alert" className="rounded-xl border border-amber-300/30 p-4 text-sm text-amber-200">{error}<Button variant="outline" className="ml-4" onClick={()=>setRetry(r=>r+1)}>Retry</Button></div>}
    {CLOUD_DEPLOYMENT&&<p className="rounded-xl border border-amber-300/30 p-4 text-sm leading-7 text-amber-200">Cloud preview: road publications and vehicle feeds are not connected. OmniView will assess selected recordings locally in batches, then publish reviewed results. The indicators below describe cloud publications, not all data stored on the local machine.</p>}
    <section aria-label="Published progress indicators" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[
      {label:'Mapped roads',value:data?.coverage.roads,icon:Map,note:'OpenStreetMap coverage'},
      {label:'Published reports',value:data?.reports.published,icon:Activity,note:'Latest published update window'},
      {label:'In progress',value:data?.reports.in_progress,icon:Construction,note:'Published report status'},
      {label:'Resolved',value:data?.reports.resolved,icon:CheckCircle2,note:'Published resolution status'},
    ].map(m=><article key={m.label} className="rounded-2xl border border-white/10 bg-[#091827] p-5"><div className="flex justify-between text-sm text-slate-400">{m.label}<m.icon size={17} className="text-emerald-300"/></div><p className="my-3 text-3xl font-semibold text-white">{m.value===undefined?'—':m.value.toLocaleString()}</p><p className="text-xs text-slate-500">{m.note}</p></article>)}</section>
    <section><div className="mb-4 flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-widest text-slate-500">Updates with context</p><h2 className="mt-2 text-2xl font-semibold text-white">Projects & road highlights</h2></div><span className="text-xs text-slate-500">Only publication-reviewed updates</span></div>{data?.updates.length?<div className="grid gap-4 md:grid-cols-3">{data.updates.map(u=><article key={u.id} className="rounded-2xl border border-white/10 bg-[#091827] p-5"><p className="text-xs text-emerald-300">{u.category} · {u.status.replaceAll('_',' ')}</p><h3 className="mt-3 font-semibold text-white">{u.title}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{u.summary}</p><time className="mt-4 block text-xs text-slate-500" dateTime={u.updated_at}>{new Date(u.updated_at).toLocaleDateString('en-IN')}</time>{u.source_url&&<a className="mt-3 inline-block text-sm text-emerald-300 underline" href={u.source_url} target="_blank" rel="noopener noreferrer">Official source</a>}</article>)}</div>:<div className="rounded-2xl border border-dashed border-white/15 p-8"><Construction className="text-slate-500"/><h3 className="mt-3 font-semibold">{data?'No reviewed updates published yet':'Published updates will appear here'}</h3><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Government projects need an official source. Repair reports need publication review. We do not substitute sample statistics for the authority’s actual progress.</p></div>}</section>
    <section className="grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-white/10 p-6"><ScanLine className="text-amber-300"/><h2 className="mt-3 text-xl font-semibold">OmniView AI checks</h2><p className="mt-3 text-sm leading-6 text-slate-400">Model validation is in progress. Only reviewed findings approved for publication will appear on the public map. Grey roads are unassessed—not proven safe.</p><span className="mt-4 inline-block rounded-full bg-amber-300/10 px-3 py-1 text-xs text-amber-200">Validation pending</span></article><article className="rounded-2xl border border-emerald-300/20 bg-emerald-300/5 p-6"><h2 className="text-xl font-semibold">Your dashcam can help.</h2><p className="mt-3 text-sm leading-6 text-slate-400">Sign in to choose recorded footage or live road-facing capture. Camera and GPS access are separate, optional permissions.</p><Button asChild variant="outline" className="mt-5"><Link href="/contribute/login">Enter the private contributor area<ArrowUpRight size={16}/></Link></Button></article></section>
    <footer className="flex flex-wrap justify-between gap-3 border-t border-white/10 py-6 text-xs text-slate-500"><span>© OpenStreetMap contributors · West Delhi pilot · Not for navigation or enforcement</span><Link href="/contribute/privacy" className="underline">Privacy & terms</Link></footer>
  </main></div>
}
